[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  prettyURLs = true
  trailingSlash = true
  exclude = [
    # By file Path
    "./404",
    "./offline-plugin-app-shell-fallback"
  ]
